services:
  postgres:
    image: postgres:17
    container_name: postgres_pta
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=spring
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=spring
volumes:
  postgres:
